examples/basic_todo/config/routes.rb
Rails.application.routes.draw do
  constraints(format: :html) do
    resources :sign_ups, only: [:new, :create]
    resources :sign_ins, only: [:new, :create, :destroy]

    resources :todos,    only: [:index, :new, :create, :edit, :update, :destroy]

    resource :all_completed_todos, only: [:destroy], as: :all_completed_todos, controller: 'todos/all_completed'

    scope "todos/:todo_id" do
      resource :completed, only: [:create], as: :completed_todos, controller: 'todos/completed'
    end

    resources :users, only: [:index]
  end

  root to: 'home#show'
end

examples/basic_todo/app/models/ability.rb
class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user || User.new
    @user.roles.each { |role| send(role.name.downcase) }

    if @user.roles.size == 0
      guest
    end
  end

  def guest
  end

  def account_holder
    can :manage, Todo, user_id: user.id
    can :create, User
    can [:read, :update], user
  end

  def admin
    can :manage, :all
  end
end

examples/basic_todo/app/models/role.rb
class Role < ActiveRecord::Base
  has_many :user_roles
  has_many :users, through: :user_roles
end

examples/basic_todo/app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user

  validates :description, presence: true
end

examples/basic_todo/app/models/user.rb
class User < ActiveRecord::Base
  has_many :todos

  has_many :user_roles
  has_many :roles, through: :user_roles

  has_secure_password validations: false

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

examples/basic_todo/app/models/user_role.rb
class UserRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

examples/basic_todo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def view_assigns
    {}
  end
end

examples/basic_todo/app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Aldous::Controller

  controller_actions :show
end

examples/basic_todo/app/controllers/sign_ins_controller.rb
class SignInsController < ApplicationController
  include Aldous::Controller

  controller_actions :new, :create, :destroy
end

examples/basic_todo/app/controllers/sign_ups_controller.rb
class SignUpsController < ApplicationController
  include Aldous::Controller

  controller_actions :new, :create
end

examples/basic_todo/app/controllers/todos/all_completed_controller.rb
class Todos::AllCompletedController < ApplicationController
  include Aldous::Controller

  controller_actions :destroy
end

examples/basic_todo/app/controllers/todos/completed_controller.rb
class Todos::CompletedController < ApplicationController
  include Aldous::Controller

  controller_actions :create
end

examples/basic_todo/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  include Aldous::Controller

  controller_actions :index, :new, :create, :edit, :update, :destroy
end

examples/basic_todo/app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Aldous::Controller

  controller_actions :index
end

examples/basic_todo/app/helpers/application_helper.rb
module ApplicationHelper
end

examples/basic_todo/app/views/defaults/_server_error.html.slim
- provide :title, "Internal Server Error"

div style="padding: 40px"
  h1= yield(:title)

  p Boo error

  - if Rails.env.development?
    == ap errors
    - errors.each do |error|
      - if error.respond_to?(:backtrace)
        == ap error.backtrace

examples/basic_todo/app/views/defaults/bad_request.html.slim
- provide :title, "Bad Request"

div style="padding: 40px"
  h1= yield(:title)

  p Boo bad request

  - if Rails.env.development?
    == ap errors
    - errors.each do |error|
      - if error.respond_to?(:backtrace)
        == ap error.backtrace

examples/basic_todo/app/views/defaults/forbidden.html.slim
- provide :title, "Forbidden"

div style="padding: 40px"
  h1= yield(:title)

  p= error

examples/basic_todo/app/views/defaults/server_error.html.slim
- provide :title, "Internal Server Error"

div style="padding: 40px"
  h1= yield(:title)

  p Boo error

  - if Rails.env.development?
    == ap errors
    - errors.each do |error|
      - if error.respond_to?(:backtrace)
        == ap error.backtrace

examples/basic_todo/app/views/home/show.html.slim
- provide :title, "Home"

= render header_view.template

h1 You must get todos

examples/basic_todo/app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"

    - if content_for?(:title)
      title= yield(:title)
    - else
      title Todos App

    meta name="viewport" content="width=device-width, initial-scale=1.0"

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  body
    = yield

examples/basic_todo/app/views/modules/_header.html.slim
.header
  .header__container
    = link_to 'Home', root_path, class: 'header__home-link'
    .header__authentication
      - if current_user
        span.header__authenticated-user
          = current_user.email
          '  |
        = button_to 'Sign Out', sign_in_path(current_user), method: :delete, class: 'header__sign-out-link'
      - else
        = link_to 'Sign In', new_sign_in_path, class: 'header__sign-in-link'
        '  |
        = link_to 'Sign Up', new_sign_up_path, class: 'header__sign-up-link'

examples/basic_todo/app/views/sign_ins/new.html.slim
- provide :title, "Sign In"

= render header_view.template

h1 Sign In

div
  = form_for user, url: sign_ins_path(user) do |f|
    = f.label :email
    = f.text_field :email
    = f.label :password
    = f.text_field :password
    = f.submit 'Sign In'

examples/basic_todo/app/views/sign_ups/new.html.slim
- provide :title, "Sign Up"

= render header_view.template

h1 Sign Up

div
  = form_for user, url: sign_ups_path(user) do |f|
    = f.label :email
    = f.text_field :email
    = f.label :password
    = f.text_field :password
    = f.submit 'Sign Up'

examples/basic_todo/app/views/todos/edit.html.slim
- provide :title, "Edit Todo"

= render header_view.template

h1 Edit Todo

div
  = form_for todo, url: todo_path(todo) do |f|
    = f.label :description
    = f.text_field :description
    = f.hidden_field :user_id
    = f.submit 'Update'

examples/basic_todo/app/views/todos/index.html.slim
- provide :title, "View Todos"

= render header_view.template

h1 Your Todos

= link_to 'Create New Todo', new_todo_path
= button_to 'Delete Completed Todos', all_completed_todos_path, method: :delete

- todo_views.each do |todo_view|
  = render todo_view.template

examples/basic_todo/app/views/todos/index_view/_todo.html.slim
div
  span= description
  '  |
  span= done
  span= link_to 'Update', edit_todo_path
  span= button_to 'Delete', delete_todo_path, method: :delete
  span= button_to 'Complete', complete_todo_path, method: :post
hr

examples/basic_todo/app/views/todos/new.html.slim
- provide :title, "New Todo"

= render header_view.template

h1 New Todo

div
  = form_for todo, url: todos_path(todo) do |f|
    = f.label :description
    = f.text_field :description
    = f.hidden_field :user_id
    = f.submit 'Create'

examples/basic_todo/app/views/todos/not_found.html.slim
- provide :title, "Not Found"

div style="padding: 40px"
  h1= yield(:title)

  p= "No todo with id #{todo_id}, for user #{user_email}"

examples/basic_todo/app/views/users/index.html.slim
- provide :title, "Users"

= render header_view.template

h1 Users
- user_views.each do |user_view|
  = render user_view

examples/basic_todo/app/views/users/index_view/_user.html.slim
div= email
hr